config/routes.rb
Binkity::Application.routes.draw do

  devise_for :users
  resources :pictures

  resources :posts, except: :show

  get '/home', to: 'home#index', as: 'home'
  get '/gallery', to: 'home#gallery', as: 'gallery'
  get '/about', to: 'home#about', as: 'about'
  get '/shopping_cart', to: 'home#cart', as: 'cart'

  match '/contact', to: 'home#contact_new', as: 'contact', via: [:get]
  match '/contact', to: 'home#contact_create', as: 'contact_create', via: [:post]

  root 'home#index'

  

end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :email, :content

  validates :email, :content, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_and_belongs_to_many :posts
  mount_uploader :file, FileUploader
  validates :file, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_and_belongs_to_many :pictures
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable


  def admin?
    if self.user_type == "admin"
      true
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.order(updated_at: :desc)
  end

  def gallery
    if params[:filter].blank?
      @pictures = Picture.all
    else
      @pictures = Picture.where("#{params[:filter]} = ?", true)
    end
    @filters = [{name: "Wszystkie", id: ''}, {name: "Bransoletki", id: 'is_bracelet'}, {name: "Kolczyki", id: 'is_earring'}, {name: "Naszyjniki", id: 'is_necklace'}, {name: "Komplety", id: 'is_set'}, {name: "Pozostałe", id: 'is_other'}]
  end

  def about
  end

  def cart
  end

  def contact_new
    @message = Message.new
  end

  def contact_create
    @message = Message.new(params[:message])

    if @message.valid?
      ContactMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      render action: 'contact_new'
    end
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_picture, only: [:show, :edit, :update, :destroy]


  def index
    @pictures = Picture.all
  end


  def show
  end


  def new
    @picture = Picture.new
  end


  def edit
  end


  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render action: 'show', status: :created, location: @picture }
      else
        @arts = [{name: "Bracelet", id: 1}, {name: "Earrings", id: 2}]
        format.html { render action: 'new' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        @arts = [{name: "Bracelet", id: 1}, {name: "Earrings", id: 2}]
        format.html { render action: 'edit' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end

  private
    def set_picture
      @picture = Picture.find(params[:id])
    end

    def picture_params
      params.require(:picture).permit(:description, :art, :file, :is_bracelet, :is_earring, :is_necklace, :is_set, :is_other)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_filter :is_admin
  before_action :set_post, only: [:edit, :update, :destroy]


  def index
    @posts = Post.all
  end


  def new
    @post = Post.new
    @pictures = Picture.order('updated_at DESC')
  end


  def edit
    @pictures = Picture.order('updated_at DESC')
  end


  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: 'Post was successfully created.' }
        format.json { head :no_content }
      else
        @pictures = Picture.order('updated_at DESC')
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_url, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        @pictures = Picture.order('updated_at DESC')
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :description, picture_ids: [])
    end

    def is_admin
      unless current_user.admin?
        redirect_to :root, alert: "Access denied!"
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/_admin_nav.html.erb
<%= link_to "Home", root_path %>
<%= link_to "Gallery", gallery_path %>
<%= link_to "About", about_path %>
<%= link_to "Contact", contact_path %>
<%= link_to "Posts", posts_path %>
<%= link_to "Pictures", pictures_path %>
<%= button_to 'Logout', destroy_user_session_path, :method => :delete  %>
<%= current_user.email %>
<br />
<br />

app/views/home/_nav.html.erb
<%= link_to "Home", root_path %>
<%= link_to "Gallery", gallery_path %>
<%= link_to "About", about_path %>
<%= link_to "Contact", contact_path %>

<br />
<br />

app/views/home/_user_nav.html.erb
<%= link_to "Home", root_path %>
<%= link_to "Gallery", gallery_path %>
<%= link_to "About", about_path %>
<%= link_to "Contact", contact_path %>
<%= link_to "Shopping Cart", cart_path %>
<%= button_to 'Logout', destroy_user_session_path, :method => :delete  %>
<%= current_user.email %>
<br />
<br />

app/views/home/about.html.erb
<h1>About</h1>
<br />

Mam na imię Sabinka, na co dzień zajmuję się tworzeniem stron internetowych.<br />
Biżuterię projektuję hobbystycznie od 3 lat.<br />
Specjalizuję się w bransoletkach typu shamballa oraz wszelakich wariacjach rzemieniowych.<br />
Binkabox to butik, w którym na pewno znajdziesz coś dla siebie i dla bliskich!<br />

app/views/home/cart.html.erb
<h1>Shopping Cart</h1>
<br />

Coming up soon!

app/views/home/contact_new.html.erb
<h1>Contact</h1>
<br />

<%= form_for @message, :url => contact_path do |f| %>
    <% if @message.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@message.errors.count, "error") %> prohibited this picture from being saved:</h2>

          <ul>
            <% @message.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :email %>
      <%= f.email_field :email, value: user_signed_in? ? current_user.email : nil %>
    </div>

    <div class="field">
      <%= f.label :message %>
      <%= f.text_area :content %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/home/gallery.html.erb
<h1>Gallery</h1>
<br />

<%= select_tag 'filtering', options_for_select(@filters.collect{ |f| [f[:name], f[:id]] }, selected: "#{params[:filter]}") %>

<%= render_gallery_for @pictures, title: 'description'%>

<script>
    $('#filtering').change(function(){
        value = $("#filtering").val();
        path  = "<%= gallery_path %>";
        if( value == "" )
            window.location = path;
        else
            window.location = path+"?filter="+value;
        end
    });
</script>

app/views/home/index.html.erb
<h1>Index</h1>
<br />

<% @posts.each do |post| %>
      <%= post.title %> <br />
      <%= post.description %>
      <%= render_gallery_for post.pictures, title: 'description'%>
      <br /><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Binkity</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
    <% if current_user.admin? %>
        <%= render 'home/admin_nav' %>
    <% else %>
        <%= render 'home/user_nav' %>
    <% end %>
<% else %>
    <%= render 'home/nav' %>
<% end %>
<%= yield %>

</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
    <% if @picture.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

          <ul>
            <% @picture.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :bracelet %><br>
      <%= f.check_box :is_bracelet, {}, "true", "false" %>
    </div>
    <div class="field">
      <%= f.label :earrings %><br>
      <%= f.check_box :is_earring, {}, "true", "false" %>
    </div>
    <div class="field">
      <%= f.label :necklace %><br>
      <%= f.check_box :is_necklace, {}, "true", "false" %>
    </div>
    <div class="field">
      <%= f.label :set %><br>
      <%= f.check_box :is_set, {}, "true", "false" %>
    </div>
    <div class="field">
      <%= f.label :other %><br>
      <%= f.check_box :is_other, {}, "true", "false" %>
    </div>
    <div class="field">
      <%= f.label :file %><br>
      <%= f.file_field :file %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>Pictures</h1>

<table>
  <thead>
  <tr>
    <th></th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @pictures.each do |picture| %>
      <tr>
        <td><%= image_tag(picture.file.thumbnail.url, width: "80") %></td>
        <td><%= picture.description %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>
<br />

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @picture.description %>
</p>

<p>
  <strong>Bracelet:</strong>
  <%= @picture.is_bracelet %>
</p>
<p>
  <strong>Earrings:</strong>
  <%= @picture.is_earring %>
</p>
<p>
  <strong>Necklace:</strong>
  <%= @picture.is_necklace %>
</p>
<p>
  <strong>Set:</strong>
  <%= @picture.is_set %>
</p>
<p>
  <strong>Other:</strong>
  <%= @picture.is_other %>
</p>

<p>
  <strong>File:</strong>
  <%= image_tag(@picture.file.url) %>
</p>



<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>

app/views/posts/_form.html.erb
<style>
    #feedback { font-size: 1.4em; }
    #selectable .ui-selecting { background: #FECA40; }
    #selectable .ui-selected { background: #F39814; color: white; }
    #selectable { list-style-type: none; margin: 0; padding: 0; width: 450px; }
    #selectable li { margin: 3px; padding: 1px; float: left; width: 100px; height: 80px; font-size: 4em; text-align: center; }
</style>


<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <%=collection_check_boxes(:post, :picture_ids, Picture.all, :id, :description)%>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Desciption</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>